### ISSUE TITLE
play button

### ISSUE THREAD

**Issue by LordoftheWild** [LordoftheWild/Eternal-Forest#15]
k, i'm sorry for being a noob
but can someone make the play button actually apper?
thanks!

**Comment by Bergenfrundt** [comment]
>apper

bruh

**Comment by LordoftheWild** [comment]
*appear
(my keyboard is not very sensitive)

**Comment by LordoftheWild** [comment]
the button appears

**Comment by Bergenfrundt** [comment]
thanks to me
