### ISSUE TITLE
play button

### ISSUE THREAD

**Issue by LordoftheWild** [LordoftheWild/Eternal-Forest#17]
the button does not work.
(maybe it's not connected to the controller.js file)
(if so then we have to 'assign' it to the controller.js)

**Comment by Loquacious** [comment]
Are you kidding me? It's simply not working because `game` is undefined since in `script.js`, you never properly defined your variables causing an error. Also, it appears because it's clearly put in the HTML. Did you not test the game once before committing it?

> maybe it's not connected to the controller.js file

Connected?

**Comment by LordoftheWild** [comment]
ok, I am not sure what you mean

**Comment by LordoftheWild** [comment]
and by not connected I meant that the two were not linked in any way

**Comment by LordoftheWild** [comment]
"It's simply not working because  game  is undefined since in  script.js , you never properly defined your variables causing an error."
what do you mean?

**Comment by Loquacious** [comment]
https://github.com/LordoftheWild/Eternal-Forest/blob/c6b4a03b1a6a5a8989b400e90da3030b948bd193/scripts/script.js

You used commas and the `var` key word which is the incorrect way of defining variables. You fixed it later with [commit dbec017471f7dd2761abfdff95866accc558bc6f](https://github.com/LordoftheWild/Eternal-Forest/commit/dbec017471f7dd2761abfdff95866accc558bc6f).

**Comment by LordoftheWild** [comment]
did I fix it?
oh well it works now
so we're all good
