### ISSUE TITLE
Desicions Decisions

### ISSUE THREAD

**Issue by LordoftheWild** [LordoftheWild/Eternal-Forest#24]
we now must decide, will we be continuing with the story or should we add the graphics first and also, when should we do the saving features?

**Comment by earthkit2** [comment]
I'm tied between graphics and story, but the saving can wait

**Comment by earthkit2** [comment]
but if we don't do saving first then it twould make sense if we don't do the story because if we have a long story and no saving feature you would have to play the whole thing

**Comment by earthkit2** [comment]
but I do wanna extend the story

**Comment by LordoftheWild** [comment]
you know what, let's do graphics and then saving that way we have to write less code. because if we do saving first, when we add the graphics we would have to change the code to make it work with graphics.
