### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by LordoftheWild** [LordoftheWild/Eternal-Forest#27]
can somebody either help me get the graphics up or help me revert the thing to v0.0.2. thanks.

**Comment by Bergenfrundt** [comment]
This is git, reverting things is rather quite easy. 

Can you tell me what specific commit you want it reverted to? MEaning like after every change it's labeled as a commit; go into the code section and click commits and pick which one you want to revert to

**Comment by LordoftheWild** [comment]
merge pull request #25 from LordoftheWild-patch

**Comment by LordoftheWild** [comment]
there that should do it

**Comment by LordoftheWild** [comment]
Well that didn't work

**Comment by LordoftheWild** [comment]
nvm I got it
